### ISSUE TITLE
File gem/utils/embed_utils.py does not exist in repository

### ISSUE THREAD

**Issue by AmroAlJundi** [palash1992/GEM-Benchmark#1]
**Describe the bug**
While trying to run the script `gem/experiments/exp.py` script, I got the following error:
```
Traceback (most recent call last):
    File "exp.py", line 19, in <module>
        from gem.evaluation.evaluate_link_prediction import expLP, expLPT
    File "/home/{username}/GEM-Benchmark/gem/evaluation/evaluate_link_prediction.py", line 12, in <module>
        from gem.utils import embed_util                                                                                                                                                                               ImportError: cannot import name 'embed_util' from 'gem.utils' (/home/{username}/GEM-Benchmark/gem/utils/__init__.py) 
```
The file gem/utils/embed_utils.py doesn't seem to be in the master branch of the repository.

**To Reproduce**
1. Execute  command `git clone https://github.com/palash1992/GEM-Benchmark`
2. navigate to GEM-Benchmark
3. Rename the directory `gem-ben` to `gem` 
4. Execute  command `pip3 install -r requirements.txt --user`
5. Execute command `export PYTHONPATH=$PYTHONPATH:/home/{username}/GEM-Benchmark`
6. Navigate to gem/experiments/
7. Execute command `python exp.py`

**Expected behavior**
The script exp.py to run without errors.

**Desktop:**
 - OS: Ubuntu 16.04
 - Python: 3.6.9
 
**Additional context**
I had the project GEM installed but it was preventing this project from running so I had to first uninstall it. Figured I'd mention this detail. Also, the file wouldn't run without me changing the directory `GEM-Benchmark/gem-ben` to `GEM-Benchmark/gem`.

Thank you.

**Comment by breakanalysis** [comment]
I also noticed this, but it seems embed_util is not used, so probably that line can be removed
